import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootProvider from "@/components/RootProvider";
import { Toaster } from "@/components/ui/Sonner";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Harsh Sandhu",
  description: "Generated by create next app",
};

interface Props extends PropsWithChildren { }

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <RootProvider>
          {children}
          <Toaster richColors closeButton className="print:hidden" />
        </RootProvider>
      </body>
    </html>
  );
}
